from django.conf.urls import url
from simplemooc.courses import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(
        r'^solicitar-curso/$',
        views.create_course_request,
        name='create_course_request'
    ),
    url(
        r'^cursos/trb/$',
        views.list_courses_trb,
        name='list_courses_trb'
    ),
    url(
        r'^cursos/normal/$',
        views.list_courses_normal,
        name='list_courses_normal'
    ),
    url(
        r'^curso/(?P<pk>\d+)/$',
        views.course,
        name='course'
    ),
    url(
        r'^curso/(?P<pk>\d+)/criar-licao/$',
        views.create_lesson,
        name='create_lesson'
    ),
    url(
        r'^curso/(?P<pk>\d+)/licao/(?P<lesson_pk>\d+)/$',
        views.view_lesson,
        name='view_lesson'
    ),
    url(
        r'^curso/(?P<pk>\d+)/editar-licao/(?P<lesson_pk>\d+)$',
        views.edit_lesson,
        name='edit_lesson'
    ),
    url(
        r'^curso/(?P<c_pk>\d+)/licao/(?P<l_pk>\d+)/add-material$',
        views.create_material_lesson,
        name='create_material_lesson'
    ),
    url(
        r'^curso-trb/(?P<pk>\d+)/$',
        views.course_trb,
        name='course_trb'
    ),
    url(
        r'^curso/(?P<pk>\d+)/criar-licao-trb/$',
        views.create_lesson_trb,
        name='create_lesson_trb'
    ),
    url(
        r'^curso/(?P<pk>\d+)/editar-licao-trb/(?P<lesson_pk>\d+)$',
        views.edit_lesson_trb,
        name='edit_lesson_trb'
    ),
    url(
        r'^curso/(?P<c_pk>\d+)/licao-trb/(?P<l_pk>\d+)/add-material$',
        views.create_material_lesson_trb,
        name='create_material_lesson_trb'
    ),
    url(
        r'^curso/(?P<pk>\d+)/licao-trb/(?P<lesson_pk>\d+)/$',
        views.view_lesson_trb,
        name='view_lesson_trb'
    ),
    url(
        r'^curso/(?P<pk>\d+)/lesson/(?P<lesson_pk>\d+)/nivel-conhecimento/$',
        views.add_knowledge_level,
        name='add_knowledge_level'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/nivel-conhecimento/(?P<n_pk>\d+)/$',
        views.delete_knowledge_level,
        name='delete_knowledge_level'
    ),
    url(
        r'^curso-trb/(?P<course_pk>\d+)/lesson/(?P<lesson_pk>\d+)/add-descricao-verbo/(?P<cat_pk>\d+)/$',
        views.add_verb_description,
        name='add_verb_description'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/editar-descricao/(?P<v_pk>\d+)/categoria/(?P<cat_pk>\d+)/$',
        views.edit_verb_description,
        name='edit_verb_description'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/deletar-descricao/(?P<v_pk>\d+)/$',
        views.delete_verb_description,
        name='delete_verb_description'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/lesson/(?P<l_pk>\d+)/add-categoria-processo-cognitivo/(?P<n_pk>\d+)$',
        views.add_category_cognitive,
        name='add_category_cognitive'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/deletar-categoria-processo-cognitivo/(?P<cat_pk>\d+)$',
        views.delete_category_cognitive,
        name='delete_category_cognitive'
    ),
    url(
        r'^curso-trb/(?P<c_pk>\d+)/lesson/(?P<l_pk>\d+)/visualizar-tabela/$',
        views.get_trb_table,
        name='get_trb_table'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/$',
        views.details,
        name='details'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/inscricao/$',
        views.enrollment,
        name='enrollment'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/cancelar-inscricao/$',
        views.undo_enrollment,
        name='undo_enrollment'
    ),
    url(
        r'^(?P<course_slug>[\w_-]+)/criar-anuncio/$',
        views.create_announcement,
        name='create_announcement'
    ),
    url(
        r'^(?P<course_slug>[\w_-]+)/listar-anuncios/$',
        views.list_announcements,
        name='list_announcements'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/anuncios/$',
        views.announcements,
        name='announcements'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)/$',
        views.show_announcement,
        name='show_announcement'
    ),
    url(
        r'^(?P<course_slug>[\w_-]+)/anuncios-curso/(?P<announcement_pk>\d+)/$',
        views.show_announcement_to_professor,
        name='show_announcement_to_professor'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/aulas/$',
        views.lessons,
        name='lessons'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/aulas/(?P<pk>\d+)/$',
        views.lesson,
        name='lesson'
    ),
    url(
        r'^(?P<course_slug>[\w_-]+)/professor/materiais/(?P<pk>\d+)/$',
        views.show_material_to_professor,
        name='show_material_to_professor'
    ),
    url(
        r'^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)/$',
        views.material,
        name='material'
    ),
]
